[package]
name = "sly_sudoku"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.8" }
bevy-inspector-egui = { version = "0.13" }
iyes_loopless = { version = "0.8" }
iyes_progress = { version = "0.6", features = [] }
bevy_asset_loader = { version = "0.13", features = [
    "stageless",
    "progress_tracking_stageless"
] }
strum = "0.24"
strum_macros = "0.24"